### ISSUE TITLE
Error: HTTP Observatory is down

### ISSUE THREAD

**Issue by faizan-official** [mozilla/http-observatory#524] opened 2024-02-05 03:48 UTC
For some reason, the tool is down and I believe it's due to CORS. Can anyone please look into this and resolve it.
![image](https://github.com/mozilla/http-observatory/assets/34148227/2636bcfa-f88d-4384-aed8-49f27c723617)

**Comment by gene1wood** [comment] 2024-02-15 20:43
@faizan-official Are you still seeing this issue (I'm not able to reproduce it)

**Comment by Sandr0x00** [comment] 2024-03-27 13:31
Do you maybe have some AdBlock active? Was the issue at my side. Whitelisting fixed it for me.

**Comment by gene1wood** [comment] 2024-03-27 16:57
I'll close this out, not hearing back from @faizan-official

**Closed by gene1wood** 2024-03-27 16:57 UTC
